### PR TITLE
Adds start and stop server operations API 

### PR DESCRIPTION
**Pull request by amirfefer**
Server operations API:
[Start specified server](https://developer.rackspace.com/docs/cloud-servers/v2/api-reference/svr-basic-operations/#start-specified-server)
[Stop specified server](https://developer.rackspace.com/docs/cloud-servers/v2/api-reference/svr-basic-operations/#stop-specified-server)

### CODE REVIEW

**Comment by shlomizadok** [comment]
@amirfefer - thanks for this PR, please note the failing tests

**Comment by shlomizadok** [comment]
@mdarby - test failures seem unrelated. Would you mind testing (/me got no Rackspace credentials) and we'd love to see this feature in (corresponds to issue [#17898](http://projects.theforeman.org/issues/17898]) at theforeman project. Thanks!

**Comment by mdarby** [comment]
Testing this today.

**Comment by shlomizadok** [comment]
@mdarby - You are a good man, Charlie Brown
image

**Comment by mdarby** [comment]
Looks nice and works like a charm. Thank you!

**Comment by mdarby** [comment]
Merged and pushed the v0.1.4 gem.

**Pull request merged**
